In [7]:
import pandas as pd

In [9]:
path = 'C:/Users/Joshua/PycharmProjects/instagram/insta.txt'

In [21]:
insta = pd.read_csv(path, encoding='utf-8')
insta.drop('Unnamed: 0', axis=1, inplace = True)

In [5]:
insta.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,plate.diary,그릇일기,동백라인,여기담기,찬합,여경란작가,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,psuceramics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,plate.diary,여기담기,일상,맛있는브로콜리머리,심스,그릇일기,반성의식단,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,siktam_ceramic,전상근작가,백자,전상근도자기,그릇장,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,oh.rina_studio,characterdesign,도자기,character,illustration,일러스트,ceramics,손그림,세라믹토이,캐릭터디자인,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN